### ISSUE TITLE
Enums

### ISSUE THREAD

**Issue by ohbob** [YsarocK/fetch-appwrite-types#53]
Enums type is returned as string. 

ps: awesome library!

**Comment by YsarocK** [comment]
Hi!

Will give a look tomorrow, I keep you in touch.

Good to know it's helpful 🙏

**Comment by YsarocK** [comment]
Done man, Enums are now created & referenced in types.

You can update to [v1.3.1](https://github.com/YsarocK/fetch-appwrite-types/releases/tag/v1.3.1).

Have a good day!
