### ISSUE TITLE
[Bug] Param "outFileName" doesn't work

### ISSUE THREAD

**Issue by cogscides** [YsarocK/fetch-appwrite-types#57]
When I'm running the command:
`npx fetch-appwrite-types outDir ./src/lib/database outFileName \"appwrite.d\" hardTypes`
it just creates the file but writes types to the default `appwrite.ts` file in a specified directory.

**Comment by YsarocK** [comment]
Hello @cogscides,

Found the issue, will release a fix this day.

**Comment by YsarocK** [comment]
That should be fixed in 1.8.1. Thanks for the feedback!
